name: SimpleAuth
main: SimpleAuth\SimpleAuth
version: 2.1.2-6
api: [3.0.0-ALPHA11]
load: STARTUP
author: PocketMine Team
authors: [shoghicp]
description: Prevents people from impersonating an account, requires registration and login when connecting.
website: https://github.com/PocketMine/SimpleAuth
commands:
 link:
  description: "Links an account"
  usage: "/link <other account><other password>"
  permission: simpleauth.command.link
 unlink:
  description: "Unlinks linked accounts"
  usage: "/unlink"
  permission: simpleauth.command.unlink

permissions:
 simpleauth:
  default: op
  description: "Allows using everything SimpleAuth has"
  children:
   simpleauth.lastid:
    description: "Allows authenticating using the last id when enabled in the config"
    default: true
    children:
     simpleauth.command.login:
      description: "Allows logging into an account"
      default: true
     simpleauth.command.link:
      description: "Allows linking to another account"
      default: true
     simpleauth.command.unlink:
      description: "Allows unlinking an account"
      default: true
